steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - gcp-ui-new
      - '--source=.'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--entry-point=serve'
      - '--set-env-vars=NODE_ENV=production'

options:
  logging: CLOUD_LOGGING_ONLY
