steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'gcp-ui-new',
      '--source=.', '--region=us-central1',
      '--platform=managed',
      '--allow-unauthenticated'
    ]
